name: Build Kernel H2OS
on:
  push:
    branches:    
      - makiras_10

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/Makiras/op5.git -b makiras_10 --depth=1 
    - name: Build With Shell
      run: |
        cd ~/op5
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cp op5/AnyKernel ./ -r
        cd AnyKernel/
        cp ../op5/out/arch/arm64/boot/Image.gz-dtb  ./

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blu_spark_makiras_10
        path: /home/runner/AnyKernel/

